### ISSUE TITLE
editorConnect ekraani JS pole loodud

### ISSUE THREAD

**Issue by kmiljan** [harry-vipper/Tarkvara-Projekt-IAS1410#7]
editorConnect ekraan peab avanema, kui tahame ühendada seadet editorile ligipääsemiseks.

Ekraanil tuleb implementeerida on fade in, fade out transitsioonid.

SSID ja parool genereeritakse tulevikus automaatselt. Selleks peab seni olema tühi funktsioon, mis väljastab viisakalt nimetatud vaikenime SSID ja parooli jaoks (nt ühe objektina). Sellel funktsioonil peab olema üks parameeter, mis on tõese väärtusega siis, kui genereeritakse SSID-d päris WiFi AP jaoks - sellest tuleb edasi juttu.

SSID peab olema ka kõrvaloleval SVG pildil. Eraldi on taust ekraaniga, ja "leitud WiFi võrkude" sissekanded. Sissekanded peavad olema dünaamiliselt genereeritud ja vastavasse konteinerelementi pandavad. Kui pannakse päris WiFi AP SSID-d, siis jääb puudu üks class (pööra tähelepanu HTMLile) ja generaatorfunktsioonile antakse tõene sisend. Vastasel juhul väär sisend. Eesmärk on tulevikus genereerida suvalistest sõnadest koosnevaid SSID-sid.

SSID pikkus võiks olla kuidagi piiratud, sest need ei tule muidu SVG pildile korrektselt enam. Tähtede kogus on ebatäpne lahendus.

Juhend näitab ka URL-i, millele kasutajal navigeerida tuleb.

See ekraan override'ib värvid. Ma korrastan need peale seda, kui see on implementeeritud, et footeri värvid oleks aksepteeritavad.

**Comment by harry-vipper** [comment]
SSID/PW genereerimine ja pikkuse kontroll implementeerimata
